#!/bin/sh
set -ex

# Ask for the administrator password right away
sudo -v

### General
# Set the menu bar and Dock to dark
defaults write NSRequiresAquaSystemAppearance -bool true

# Set highlight color to graphite
defaults write NSGlobalDomain AppleHighlightColor -string "0.847059 0.847059 0.862745"

# Set appearance for buttons, menus, and windows to blue
defaults write NSGlobalDomain AppleAquaColorVariant -int 1

### Dock
# Set the Dock size
defaults write com.apple.dock tilesize -int 36

# Enable magnification
defaults write com.apple.dock magnification -bool true

# Set the magnification size
defaults write com.apple.dock largesize -int 50

# Automatically hide the Dock
defaults write com.apple.dock autohide -bool true

# Set Dock opening delay
defaults write com.apple.Dock autohide-delay -float 0

# Do not show recent applications
defaults write com.apple.dock show-recents -bool false

# Disable most recently used spaces reordering
defaults write com.apple.dock mru-spaces -bool false

# Reduce delay for workspace switching via edges
defaults write com.apple.dock workspaces-edge-delay -float 0.1

# Disable swoosh animation for workspace switches
defaults write com.apple.dock workspaces-swoosh-animation-off -bool true

### Security & Privacy
# Require password immediately after sleep or screen saver begins
defaults write com.apple.screensaver askForPassword -bool true
defaults write com.apple.screensaver askForPasswordDelay -int 0

# Uncheck "Save in Keychain" by default in `pinentry-mac`
defaults write org.gpgtools.pinentry-mac UseKeychain -bool NO

### Language & Region
# Use English language with Danish regional format (en_DK)
defaults write NSGlobalDomain AppleLocale -string "en_DK"

# Use centimeters for measurement units
defaults write NSGlobalDomain AppleMeasurementUnits -string "Centimeters"

### Sound
### Keyboard
# Set key repeat to fast, and delay until repeat to short
defaults write NSGlobalDomain KeyRepeat -int 2
defaults write NSGlobalDomain InitialKeyRepeat -int 15

# Disable automatic spelling correction
defaults write NSGlobalDomain NSAutomaticSpellingCorrectionEnabled -bool false

# Disable automatic word capitalization
defaults write NSGlobalDomain NSAutomaticCapitalizationEnabled -bool false

# Disable full stops with double-space
defaults write NSGlobalDomain NSAutomaticPeriodSubstitutionEnabled -bool false

# Disable smart quotes and dashes
defaults write NSGlobalDomain NSAutomaticQuoteSubstitutionEnabled -bool false
defaults write NSGlobalDomain NSAutomaticDashSubstitutionEnabled -bool false

# Quit Ghostty with Alt+Cmd+Q
defaults write com.mitchellh.ghostty NSUserKeyEquivalents -string '{ "Quit Ghostty" = "@~q"; }'

# Quit Firefox with Alt+Cmd+Q
defaults write org.mozilla.firefoxdeveloperedition NSUserKeyEquivalents -string '{ "Quit Firefox" = "@~q"; }'

# Use keyboard navigation to move focus between controls
defaults write NSGlobalDomain AppleKeyboardUIMode -int 3

### Trackpad
# Enable tap to click
defaults -currentHost write NSGlobalDomain com.apple.mouse.tapBehavior -int 1
defaults write NSGlobalDomain com.apple.mouse.tapBehavior -int 1
defaults write com.apple.AppleMultitouchTrackpad Clicking -bool true

# Enable taps with three fingers (Look Up & Data Detectors)
defaults write com.apple.AppleMultitouchTrackpad.plist TrackpadThreeFingerTapGesture -int 2

# Set trackpad sensitivity
defaults write NSGlobalDomain com.apple.trackpad.scaling -float 0.5

### Finder
# Show external disks, CDs, DVDs, and iPods on the desktop
defaults write com.apple.finder ShowHardDrivesOnDesktop -bool false
defaults write com.apple.finder ShowExternalHardDrivesOnDesktop -bool true
defaults write com.apple.finder ShowRemovableMediaOnDesktop -bool true
defaults write com.apple.finder ShowMountedServersOnDesktop -bool false

# Show the Home folder when opening new Finder windows
defaults write com.apple.finder NewWindowTarget -string "PfHm"

# Show all filename extensions
defaults write NSGlobalDomain AppleShowAllExtensions -bool true

# Show warning before changing an extension
defaults write com.apple.finder FXEnableExtensionChangeWarning -bool true

# Show warning before emptying the Trash
defaults write com.apple.finder WarnOnEmptyTrash -bool true

# Always open windows in icon view
defaults write com.apple.finder FXPreferredViewStyle -string "icnv"

# Group files in Finder by kind
defaults write com.apple.finder FXPreferredGroupBy -string "Kind"

# Arrange items within groups alphabetically by name
defaults write com.apple.finder FXArrangeGroupViewBy -string "Name"

# Keep folders on top when sorting by name
defaults write com.apple.finder _FXSortFoldersFirst -bool true

# Set default Finder view to arrange by name with icons set to 64x64 pixels,
# grid spacing of 54, and label position to bottom
defaults write com.apple.finder FK_DefaultIconViewSettings \
  '{ "IconViewSettings" = { "arrangeBy" = "name"; "gridSpacing" = 54; "iconSize" = 64; "labelOnBottom" = 1; }; }'

# Set sidebar icon size to medium
defaults write NSGlobalDomain NSTableViewDefaultSizeMode -int 2

# Show the status bar in Finder
defaults write com.apple.finder ShowStatusBar -bool true

# Empty the trash securely by default
defaults write com.apple.finder EmptyTrashSecurely -bool true

# Save screenshots to the ~/Desktop
defaults write com.apple.screencapture location -string "$HOME/Desktop"

# Save screenshots in `.png` format
defaults write com.apple.screencapture type -string "png"

# Disable writing `.DS_Store` files on network or USB volumes
defaults write com.apple.desktopservices DSDontWriteNetworkStores -bool true
defaults write com.apple.desktopservices DSDontWriteUSBStores -bool true

### Miscellaneous
# Do not offer new disks for Time Machine backup
defaults write com.apple.TimeMachine "DoNotOfferNewDisksForBackup" -bool "false"

# Set menu bar items
defaults write com.apple.systemuiserver menuExtras -array \
  "/System/Library/CoreServices/Menu Extras/AirPort.menu" \
  "/System/Library/CoreServices/Menu Extras/Battery.menu" \
  "/System/Library/CoreServices/Menu Extras/Bluetooth.menu" \
  "/System/Library/CoreServices/Menu Extras/Clock.menu" \
  "/System/Library/CoreServices/Menu Extras/TimeMachine.menu" \
  "/System/Library/CoreServices/Menu Extras/Volume.menu"

# Enable subpixel font rendering on non-Apple LCDs
defaults write NSGlobalDomain AppleFontSmoothing -int 2

# Disable crash reporter dialog
defaults write com.apple.CrashReporter DialogType none

# Disable the "Are you sure you want to open this application?" dialog
defaults write com.apple.LaunchServices LSQuarantine -bool false

### Safari Technology Preview
# Set homepage to about:blank
defaults write com.apple.SafariTechnologyPreview HomePage -string "about:blank"

# Set new windows to open with an empty page
defaults write com.apple.SafariTechnologyPreview NewWindowBehavior -int 1

# Set new tabs to open with an empty page
defaults write com.apple.SafariTechnologyPreview NewTabBehavior -int 1

# Remove history items after one year
defaults write com.apple.SafariTechnologyPreview HistoryAgeInDaysLimit -int 365

# Save downloaded files to ~/Downloads
defaults write com.apple.SafariTechnologyPreview DownloadsPath -string "$HOME/Downloads"

# Remove download list items upon successful download
defaults write com.apple.SafariTechnologyPreview DownloadsClearingPolicy -int 2

# Prevent Safari from opening "safe" files automatically after downloading
defaults write com.apple.SafariTechnologyPreview AutoOpenSafeDownloads -bool false

# Disable AutoFill web forms
defaults write com.apple.SafariTechnologyPreview AutoFillFromAddressBook -bool false
defaults write com.apple.SafariTechnologyPreview AutoFillPasswords -bool false
defaults write com.apple.SafariTechnologyPreview AutoFillCreditCardData -bool false
defaults write com.apple.SafariTechnologyPreview AutoFillMiscellaneousForms -bool false

# Set DuckDuckGo as preferred search engine
defaults write NSGlobalDomain NSPreferredWebServices '{
  NSWebServicesProviderWebSearch = {
    NSDefaultDisplayName = DuckDuckGo;
    NSProviderIdentifier = "com.duckduckgo";
  };
}'

# Suppress search suggestions
defaults write com.apple.SafariTechnologyPreview SuppressSearchSuggestions -bool true

# Warn when visiting a fraudulent website
defaults write com.apple.SafariTechnologyPreview WarnAboutFraudulentWebsites -bool true

# Ask websites not to track me
defaults write com.apple.SafariTechnologyPreview SendDoNotTrackHTTPHeader -bool true

# Disallow websites to ask for permission to send notifications
defaults write com.apple.SafariTechnologyPreview CanPromptForPushNotifications -bool false

# Show full website address in Smart Search Field
defaults write com.apple.SafariTechnologyPreview ShowFullURLInSmartSearchField -bool true

# Hide favorites bar
defaults write com.apple.SafariTechnologyPreview ShowFavoritesBar -bool false

# Show status bar
defaults write com.apple.SafariTechnologyPreview ShowStatusBar -bool true

### Transmission
# Enable IP block list, set blocklist, and auto update it
defaults write org.m0k.transmission BlocklistNew -bool true
defaults write org.m0k.transmission BlocklistURL -string "http://john.bitsurge.net/public/biglist.p2p.gz"
defaults write org.m0k.transmission BlocklistAutoUpdate -bool true

# Trash original torrent files
defaults write org.m0k.transmission DeleteOriginalTorrent -bool true

### MacDown
# Ensure open document on launch
defaults write com.uranusjr.macdown supressesUntitledDocumentOnLaunch -bool false

# Sync preview scrollbar when editor scrolls
defaults write com.uranusjr.macdown editorSyncScrolling -bool true

# Set theme to "Mou Paper+"
defaults write com.uranusjr.macdown editorStyleName -string "Mou Paper+"

# Set line spacing to 3
defaults write com.uranusjr.macdown editorLineSpacing -int 3

# Set text insets to 15
defaults write com.uranusjr.macdown editorHorizontalInset -int 15
defaults write com.uranusjr.macdown editorVerticalInset -int 15

# Limit editor width
defaults write com.uranusjr.macdown editorWidthLimited -bool true

# Set maximum width to 1000
defaults write com.uranusjr.macdown editorMaximumWidth -int 1000

# Set list marker to `-`
defaults write com.uranusjr.macdown editorUnorderedListMarkerType -int 2

# Use spaces instead of tabs
defaults write com.uranusjr.macdown editorConvertTabs -bool true

# Automatically insert line prefix for the current block
defaults write com.uranusjr.macdown editorInsertPrefixInBlock -bool true

# Set CSS theme to
defaults write com.uranusjr.macdown htmlStyleName -string "majjoha"

# Enable syntax highlighted code blocks
defaults write com.uranusjr.macdown htmlSyntaxHighlighting -bool true

# Enable TeX-like math syntax
defaults write com.uranusjr.macdown htmlMathJax -bool true

# Use dollar sign as inline delimiter
defaults write com.uranusjr.macdown htmlMathJaxInlineDollar -bool true

# Enable task list syntax
defaults write com.uranusjr.macdown htmlTaskList -bool true

# Detect Jekyll front-matter
defaults write com.uranusjr.macdown htmlDetectFrontMatter -bool true

# Disable "Tile by dragging windows to screen edges"
defaults write com.apple.WindowManager EnableTilingByEdgeDrag -int 0
