#!/bin/sh

set -e

if [ "$(git rev-parse --is-inside-work-tree)" ]; then
  printf "%s" "$(git branch --no-color | tr -d '()' | sed -e '/^[^*]/d' -e "s/* \(.*\)/\1/") #[fg=colour11]｜ #[default]"
else
  printf ""
fi
