#!/bin/sh

set -e

if ! command -v pmset > /dev/null || ! command -v ioreg > /dev/null; then
  echo "\`pmset\` or \`ioreg\` not found"
  exit
fi

battery="$(pmset -g 'batt' | tr '\n' ';' | awk '{print $8}' | tr -d '%;')"

printf "%s%%" "$battery"
