#!/usr/bin/env bash
# Basically, just change directory, initialize submodules and symlin files.

cd $HOME/.env && git submodule init && git submodule update && cd $HOME

# Symlink entire dotfiles repository.
sudo bash $HOME/.env/script/symlinktree $HOME/.env
